### ISSUE TITLE
Checkpoint 1 Ready

### ISSUE THREAD

**Issue by llandritsch** [llandritsch/Meal-and-grocery-list-builder#1]
@pawaitemadisoncollege
Checkpoint 1 is ready for review.

**Comment by llandritsch** [comment]
@awaitemadisoncollege This is a test tag

**Comment by llandritsch** [comment]
@pawaitemadisoncollege Test Tag

**Comment by pawaitemadisoncollege** [comment]
What a great project idea! Isn't it nice to be your own customer on a cool project yet again!!?  Your planning looks very thorough! Great job!  LOVE hand drawn screens!!!

You asked about DB design.  When taking on a new project, I really like to do a bit of googling to see how others have chosen to design their DBs. Maybe you've already done this,  but here's a stackoverflow discussion that might be helpful: https://stackoverflow.com/questions/45655382/database-schema-for-recipe-ingredient-measurement-amount. One approach here seems very similar to what you've done, and I agree it would work well! I think the boolean for public is a good idea; I can't think of a better way to do it!  

I realize this is all a first cut and is likely exactly what you need for the early stories, but I included a few thoughts below to help with future work:

- [ ] Tomcat authentication/authorization is on the schedule for week 7, so you may want to bump "user can log in" and "user can log out" to a bit later. 
- [ ] DB: Are there things on the User profile that should be in the Users table? Macro info?
- [ ] DB: How should the Grocery list be represented here?
- [ ] DB: How will the Recipe or ingredients be associated with a given week's menu?
- [ ] Have you thought at all about a web service or api yet?
