### ISSUE TITLE
CP3 ready

### ISSUE THREAD

**Issue by llandritsch** [llandritsch/Meal-and-grocery-list-builder#10]
@pawaitemadisoncollege CP3 is ready.  My AWS instance keeps going down so I hope you can see it while it's up! 

I'm contemplating dropping angular as the JFW class hasn't been helpful as far as adding a backend.  I'm assuming we will get to that later.  I've spent a ton of time researching and trying various things and kind of feel like I'm flailing.  It has not been a good semester and has been incredibly hard to keep up with everything.  If I'm unable to get something to work this week, I'm going to scrap it and just use jsp's and what we've learned in class.  But I'm going to give it my best effort!

**Comment by pawaitemadisoncollege** [comment]
Hang in there! 4th semester is always tough; from what I've seen you've got this!!!

Is there a certain uid/pwd I should use to access the site @andritschll ?

No worries on the angular piece - that was always a stretch goal, right?!

**Comment by llandritsch** [comment]
yes! Test user: lisa pwd: bacon

**Comment by llandritsch** [comment]
@pawaitemadisoncollege also, yes.  It was definitely a stretch goal, but I'm a bit stubborn and I really want it to work!

**Comment by pawaitemadisoncollege** [comment]
Checkpoint 3 looks good! I'm glad to hear the week 9 work provides the missing link with regard to the angular implementation!!!!
