### ISSUE TITLE
week 9 ready

### ISSUE THREAD

**Issue by llandritsch** [llandritsch/Meal-and-grocery-list-builder#11]
@pawaitemadisoncollege Week 9 is ready to go! 

You are going to want to specifically look at my front-end angular branch for this week's exercise.  I have my UI making an API call to the backend to display user data.  

This week was full of lots of wins! The weekly work filled in some missing pieces for me to get my front end to work. The hardest part has been getting the syntax for angular to work as we haven't done any of this in JSFW yet.  My husband has been a big help in pointing me in the right direction of what to google and giving me examples to model my project after.  It was also helpful that I had ample time to devote to school work this week!  I didn't feel rushed to get anything done!

**Comment by pawaitemadisoncollege** [comment]
Now you have all the pieces and should be ready to fly!!!  Glad to see you are making good use of branches too!
