### ISSUE TITLE
Week 6 Ready!

### ISSUE THREAD

**Issue by llandritsch** [llandritsch/Meal-and-grocery-list-builder#4]
@pawaitemadisoncollege Week 6 is ready! Link: http://ec2-3-142-25-155.us-east-2.compute.amazonaws.com:8080/MealAndGroceryBuilder/

![Screen Shot 2021-02-25 at 10 46 18 AM](https://user-images.githubusercontent.com/71849465/109189431-9e814a00-7759-11eb-956d-5ff4b03e0344.png)

So some real wins this week: I feel like I can actually work my way around aws with ease! My very first experience with spinning up an ec2 was in advanced php, which was a bit scary feeling, but then it was easier for my honors project, and then this almost felt like a cakewalk! Using java and tommee was VERY different than php and apache, but the similarities and previous experience helped me, especially with the ssh stuff and being prepared and knowing what the pem file and precisely how it's used! I was even able to get this working WHILE playing pretty unicorn! haha! 

The one thing that still gets me is when I click the web address in aws on the instance dashboard and it's not found.  I found in php I needed to take out the https as it's not a secure site (that's how I understood it, anyways). This time, once I dropped that and added the port, everything worked as expected. 

Other than that, I didn't really have any issues this week.  I do plan on doing more indie-project work the rest of the week so I have not updated my time log or anything yet, but all of the exercise and activity stuff is done except meeting with Anthony yet! 

This was a fun week!

**Comment by pawaitemadisoncollege** [comment]
First, the important things: I really need to better understand this **_**pretty unicorn**_** thing.  WHY aren't there explanatory pictures in #random?!

Ports are always interesting! Apache runs on 80, which tends to be the default when we access a url, and 8080 is what tomcat uses. This is configurable, but I don't necessarily see a good reason to change it at this point.

No rush on this, but I was not able to access your site this morning:

![Screen Shot 2021-02-26 at 10 43 21 AM](https://user-images.githubusercontent.com/13874466/109328855-8a078500-781f-11eb-9e76-ddade42d132b.png)

Next time you are out in AWS, can you check that all status checks are passing and that port 8080 is open to all/public.

Congrats on the early week 6 finish!

**Comment by pawaitemadisoncollege** [comment]
Great, I can see the app now:
![Screen Shot 2021-02-26 at 4 40 15 PM](https://user-images.githubusercontent.com/13874466/109363809-09627c00-7853-11eb-9210-5961a4bc7d50.png)

For week 6, it should display data too:

![Screen Shot 2021-02-26 at 4 41 00 PM](https://user-images.githubusercontent.com/13874466/109363887-357dfd00-7853-11eb-8c3c-666a19ec259f.png)

**Comment by llandritsch** [comment]
@pawaitemadisoncollege I can't believe I missed that!  I also didn't see the comment until too late last night and understand that this is late now.  However, I now have data displaying!  I didn't originally do this as I wanted to do it angular and was going to try to build out a sample page on a new branch this week.

**Comment by pawaitemadisoncollege** [comment]
Good! I was able to see the user data coming back.
