### ISSUE TITLE
Design Review

### ISSUE THREAD

**Issue by lmjakel** [llandritsch/Meal-and-grocery-list-builder#5]
@pawaitemadisoncollege @llandritsch 
I really enjoyed hearing Lisa's explanation and how passionate she is for her project! 

# Design/Code Review 1

### Reviewer: LeeAnn Jakel

|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|||Reviewer comments and suggestions go here. EVERY item should have *at least* one "kudos" and one suggestion for improvement|
|**Problem Statement**|1. Accurately describes the project's purpose.<br> 2. Is professional and free of typos, slang, etc.<br> 3. Thoroughly explains the problem and the solution.<br> 4. Is understandable by the average person.| Lisa’s problem statement is clear and incredibly thorough. I really liked how she explained not just the problem and solution but also broke down how each page will be used right on the ReadMe page where it is front and center. I also thought it was thoughtfully written so that people who aren’t necessarily hardcore athletes, or working on a specific dietary plan, can understand the purpose of the application. |
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens. <br>5. Project plan and time log are up-to-date. | The early stage of design for Lisa’s project is very clean and straightforward. Her navigation bar is simple and to the point, there will be no confusion as to which page you need to go to for the different aspects of the application. Based on the drawings Lisa created, the form to add a recipe will be thorough but concise. We discussed the Menu page having a side navigation for easy access to adding certain categories of recipes, or popular recipe suggestions, to the weekly plan as a way to streamline a quick add to the menu.|
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model. <br> 2. There are at least two 1-to-many relationships.<br> 3. The model represents good database design. <br>| The database presents the appropriate information to represent the application in a meaningful way. The tables Lisa has created have the required relationships and are well thought-out. |
|**Code**|1. Proper Maven project structure is used. <br> 2. a .gitignore file for IntelliJ Java projects has been implemented. <br> 3. There is not any redundant or copy/paste code in the JSPs or classes.<br> 4. Classes are appropriately-sized (no monster classes).<br> Property files are used appropriately: no hard-coded values. <br> 5. Logging statements are used rather than System.out.println and printStackTrace (be sure to use a search to look for these!).<br> 6. There are appropriate unit tests/code coverage.  | The code Lisa has completed thus far meets the requirements listed and seems to have the appropriate structure! |

**Comment by pawaitemadisoncollege** [comment]
@lmjakel and @llandritsch 

One thing to add to this, there are some sneaky System.out.printlns out there.  Don't you love it when instructor-provided code has built-in standards "violations"? 

![Screen Shot 2021-02-26 at 10 47 14 AM](https://user-images.githubusercontent.com/13874466/109329626-70b30880-7820-11eb-9c79-5dc210089173.png)
