### ISSUE TITLE
Week 7 Exercise Ready!

### ISSUE THREAD

**Issue by llandritsch** [llandritsch/Meal-and-grocery-list-builder#8]
@pawaitemadisoncollege Week 7 is ready for review.  I completed the exercise in my project. 

This week was pretty easy overall.  I absolutely LOVE how intellij and tomcat sort of "take care" of the log in stuff for you!  When I did my project in PHP last semester, I had to write queries and hash things and compare myself, but tomcat really seems to take care of that for you.  

Questions about security: How secure is this approach?  In PHP I was needing to trim inputs and also manually put everything through with prepared statements.  I would imagine that some of that is happening "under the hood" here? If you were dealing with financial information or other sensitive data, are there there other approaches you use for login as well (other than 2 factor authentication)?  

I didn't really struggle with anything this week, but I there were some things where I didn't exactly understand why we were doing it.  For example, putting the mysql jar file in the tomcat directory.  I don't understand why we didn't have to do that when we initially set up the db vs just for authentication. 

Lastly, I'm hoping the early finish with the exercise will help me get back on track now that life has settled down! I hope to work on the front end of the project the rest of the week so I'm able to check off some of those user stories!

**Comment by pawaitemadisoncollege** [comment]
@llandritsch Good questions! I think one of the bigger risks with this solution is the fact that you are storing the uid/pwd in your own database. I really like the option of letting somebody else handle all of that user password business - AWS Cognito does this well, and other Cloud providers have similar solutions. I'm assuming Bryan will cover Cognito in your Cloud class this semester.  Google and Facebook offer good options too (and also integrate with Cognito).  For internal applications at Amfam, we used LDAP.   So, yes! There are lots of other great options!

- [ ] I noticed that goofy ${filepath} directory is still sticking around. Do you need help getting rid of it?
- [ ] Glad to see you "locked down" both the jsp and the servlet.  Be sure to keep that up as you add more jsps and servlets!

**Comment by llandritsch** [comment]
@pawaitemadisoncollege Thank you for answering with specific services!  I completely forgot about cognito. Are there other services out there that are similar to AWS that include as many options?  AWS seems to be a handy "one stop shop" kind of thing.  I've seen one or two service companies, but I haven't really came across anything like amazon.  Granted, Im still very new and inexperienced and don't always know what to search for.  

I did try to fix my goofy ${filepath} thing but was unsuccessful.  I also didn't try that hard to figure it out because I got lost in my research of implementing angular and creating another branch to my project.  We've only been covering components in jsFramworks and haven't talked about integration with other technologies or languages at all so I've been doing a lot of googling and trial and error along with my husbands suggestions.  It's been fun! (not sarcasm. haha!)

**Comment by pawaitemadisoncollege** [comment]
I think you can blame the log42.properties file in your test resources directory. You should not need a separate log4j2.properties file for testing, just use the "production" one.

The other big cloud providers are Azure (Microsoft) and Google Cloud. They all offer pretty much the same type of services, they just call each one something slightly different, but I think if you learn one, like AWS, you can adapt to the others!
