### ISSUE TITLE
week 8 ready for review

### ISSUE THREAD

**Issue by llandritsch** [llandritsch/Meal-and-grocery-list-builder#9]
@pawaitemadisoncollege Week 8 ready for review.  Used api within indie project

The activities went really easy (except the weird issue of my project structure for activity 2, but that's more of a "dumb" mistake than actually struggling).  I wasn't planning on doing the exercise within my project this week, but I found a really awesome api that could really be useful and save me from entering in a bunch of test recipes into my database down the road? api: https://developer.edamam.com/edamam-docs-recipe-api  in case you're interested at checking out this beast.  

I really struggled at getting this to work because I was getting a giant array back and couldn't seem to figure out how to map everything and just point to one recipe instead of the whole array.  In the end, after a few hours of google, my husband helped me out by explaining how the api was working and what the data structure actually was.  In hindsight, I feel like it should have been obvious, but I think we always feel that way when looking back.  Once I understood how that worked, it was easy to figure out how to get what I needed.  I would really like to incorporate this into my project, but at this point, I'm a bit intimidated by the crazy amount of data and I'm worried that I won't be able to get it working.  However, I do like a good challenge so I think I'm still going to try! 

As of this minute, I have all weekly work done so I intend to spend the rest of the day checking off the stuff I'm behind on: the weird log thing, getting week 6 stuff up to aws (which is currently having a time out issue) and adding the grocery list stuff to the db and getting the generic dao up and working! Maybe some of that will be done by time you look at this, but I just wanted you to know that I saw all of those comments and intend to fix all of that, it's just been rough staying ahead! Yay for spring break!

**Comment by llandritsch** [comment]
update: I have fixed the ${filepath} and deployed the week 6 stuff to AWS and auth is working as it should!

**Comment by pawaitemadisoncollege** [comment]
Wow! That is quite the api and a good find! 

Next steps implementing this would be to create a class, maybe a EdamamDao that would do most of this business: https://github.com/llandritsch/Meal-and-grocery-list-builder/blob/e785995456b876e9d0e5a093cbee62990494a98c/src/test/java/entity/TestServiceClient.java#L17-L22.  

Using properties to externalize the base url and key would be on the list as well.
